### ISSUE TITLE
Mouseover on native checkbox throws Uncaught TypeError

### ISSUE THREAD

**Issue by ArgosOz** [haxeui/haxeui-html5#27]
This is a custom component.
~~~~
<hbox id="hboxRight"> 
        <checkbox native="true" selected="true"/>
        <label text="Native checkbox" style="margin-left:-6px; margin-top:2px; "/>        
</hbox>
~~~~

## Expected Behavior
No error.

## Current Behavior
Throws an Uncaught TypeError: Cannot read property 'addClass' of null onMouseOver.
Throws an Uncaught TypeError: Cannot read property 'removeClass' of null onMouseOut.

## Steps to Reproduce (for bugs)
Edit: Add -debug flag and rebuild the project using build-html5.hxml.
Go bin directory and open the index.html, activate devtools then move your mouse pointer over the checkbox.

## Test app / minimal test case
Here is the example project to reproduce the error: 
[HaxeUI.zip](https://github.com/haxeui/haxeui-html5/files/1484862/HaxeUI.zip)

## Your Environment

* Version used: Latest git.
* Environment name and version Chrome 62.0.3202.89
* Operating System and version (desktop or mobile): MacOS 10.12.4

**Comment by ianharrigan** [comment]
I couldnt actually reproduce this, but i have made a number of changes to optionboxes and checkboxes that i think will fix this - can you retest and close as appropriate? 

Cheers.

PS: checkbox comes with its own label control, so you dont need to create one: `<checkbox text="Native" ... ... />` (same with optionbox)
