### ISSUE TITLE
Empty textfield has no height

### ISSUE THREAD

**Issue by hoseyjoe** [haxeui/haxeui-html5#3]
In other targets an empty textfield has a height.  
## Expected Behavior

I would expect that the textfield height we be the same as a single line of text, if no height is provided
## Current Behavior

the tetfield height is very small
## Media

![image](https://cloud.githubusercontent.com/assets/2074385/18293104/acb84a4a-7445-11e6-8b8b-d4c2705356db.png)
## Test app / minimal test case

[Small.zip](https://github.com/haxeui/haxeui-html5/files/457911/Small.zip)

**Comment by ianharrigan** [comment]
Can you retest with latest and see if this is still an issue, i believe this should be fixed.

**Comment by hoseyjoe** [comment]
1. When I uncomment  Toolkit.theme = "native";  in the previous test case  (which needs an index.html to test in  HaxeDevelop) I get a JS error
ScrollView.hx:126 Uncaught TypeError: Cannot read property 'addComponent' of null

2. It appears **fixed** for Toolkit.theme = "native"; when the scrollview of main.xml is changed to a vbox

3. It is not fixed for when I comment that out the native theme (looks same as before) **whether or not** the scrollview of main.xml is changed to a vbox

4. It works in nme (flash, cpp) in any case

**Comment by ianharrigan** [comment]
Can this be retested? The height issue should be fixed now.

**Comment by aW4KeNiNG** [comment]
I think the OpenFL backend and NME have the same problem when I implemented the new TextField features.

**Comment by aW4KeNiNG** [comment]
Confirmed, it works now in html5 backend.

![image](https://cloud.githubusercontent.com/assets/1063719/21372050/47fcfb8c-c715-11e6-8888-f921f9e8d9b3.png)
